#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// include FFI definitions generated by bindgen
pub mod ffi;

#[macro_export]
macro_rules! static_c_string {
    ($the_string:literal) => { concat!($the_string, "\x00").as_bytes().as_ptr() as *const c_char }
}
